# Generated by Django 3.2.7 on 2021-09-30 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Processed'), (2, 'Canceled'), (3, 'Accepted')], null=True, verbose_name='Status')),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Purchase', to='book.book', verbose_name='Book')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Purchase', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
