# Generated by Django 3.2.7 on 2021-09-30 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First_name')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Second_name')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('issued', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued')),
                ('market_id', models.PositiveIntegerField(verbose_name='Publisher')),
                ('discount_shop', models.PositiveSmallIntegerField(verbose_name='Discount_shop')),
                ('discount_market', models.PositiveSmallIntegerField(verbose_name='Discount_market')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Percent')),
                ('times_to_use', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Times_to_use')),
                ('times_used', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Times_used')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='ABook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.book')),
                ('file', models.FileField(blank=True, null=True, upload_to=None, verbose_name='File')),
            ],
            bases=('book.book',),
        ),
        migrations.CreateModel(
            name='BBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.book')),
                ('symbol_type', models.PositiveSmallIntegerField(choices=[(1, 'Associative'), (2, 'Didactic'), (3, 'Combined')])),
            ],
            bases=('book.book',),
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.book')),
                ('source', models.URLField(blank=True, null=True, verbose_name='Source')),
            ],
            bases=('book.book',),
        ),
        migrations.CreateModel(
            name='PBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.book')),
            ],
            bases=('book.book',),
        ),
    ]
