# Generated by Django 3.2.7 on 2021-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='source',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Source'),
        ),
    ]
